version: "3"
services:
  db:
    container_name: "db"
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: PETLOVE
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d/

  api:
    container_name: "api"
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/server

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
